### ISSUE TITLE
Update Entity Replacement Code to include whitespace around punctuation

### ISSUE THREAD

**Issue by RocioSNg** [sfbrigade/datasci-cfa-calfresh#1]
A requirement of the Spell Corrector Code is to ignore Entity Replacement text (eg. "PERSON").  However, often times the text sits next to punctuation making parsing more complicated.  We decided to introduce a whitespace in the entity replacement module to simplify downstream processing.  If an entity is next to punctuation (commas, periods, etc) the replacement needs to include a whitespace separator.

**Comment by bleeeeee** [comment]
I made some sketch code that tries to address the issue.  There is a jupyter notebook here:

https://github.com/bleeeeee/datasci-cfa-calfresh/blob/scratch/2-Data-Processing/2-Helper-Modules/calfresh_whitespace.ipynb

**Comment by RocioSNg** [comment]
Using tokenizations as a way to separate punctuation from text so this is no longer needed
